#include <SettingValue.h>
#include <DeviceIdentity.h>

namespace SettingValue {

const String PLATFORM = "esp32";

/**
 * Returns a new string after replacing each instance of the pattern with a value generated by calling the provided
 * callback.
 */
String replaceEach(String value, String pattern, String (*generateReplacement)()) {
  while (true) {
    int index = value.indexOf(pattern);
    if (index == -1) {
      break;
    }
    value = value.substring(0, index) + generateReplacement() + value.substring(index + pattern.length());
  }
  return value;
}

/**
 * Generates a random number, encoded as a hex string.
 */
String getRandom() {
  return String(random(2147483647), HEX);
}

/**
 * Uses the station's MAC address as a per-device unique id.
 * Delegates to DeviceIdentity so #{unique_id} stays in lock-step
 * with the canonical device ID format used in certs / mothership.
 */
String getUniqueId() {
  return DeviceIdentity::macHex12();
}

/**
 * Full canonical device ID (project-mac-uid8) — same string used as
 * X.509 Subject CN, mothership deviceId, and AutoUpdate did=. Lets
 * factory_settings.ini place the canonical ID into AP SSID, hostname,
 * etc, so a single source of truth flows from build → wire.
 *
 * Caveat: with a long PROJECT_NAME (e.g. "ESPRackDemo") this string
 * is 33 chars which is one over the IEEE 802.11 SSID limit (32
 * octets). Pick `#{device_id_short}` for length-sensitive consumers.
 */
String getDeviceId() {
  return DeviceIdentity::canonical();
}

/**
 * Compact device id — "<project>-<uid8>" — drops the MAC segment
 * for length-constrained slots (AP SSID 32-octet cap, mDNS/DHCP
 * hostname practical 24-char cap). Still unique per-device because
 * uid8 comes from the eFuse hardware UID, but ~13 chars shorter.
 */
String getDeviceIdShort() {
  return DeviceIdentity::projectName() + "-" + DeviceIdentity::uidHex8();
}

String format(String value) {
  value = replaceEach(value, "#{random}", getRandom);
  value.replace("#{unique_id}", getUniqueId());
  value.replace("#{device_id_short}", getDeviceIdShort());
  value.replace("#{device_id}", getDeviceId());
  value.replace("#{platform}", PLATFORM);
  return value;
}

};  // end namespace SettingValue
