#include <SettingValue.h>
#include <DeviceIdentity.h>

namespace SettingValue {

const String PLATFORM = "esp32";

/**
 * Returns a new string after replacing each instance of the pattern with a value generated by calling the provided
 * callback.
 */
String replaceEach(String value, String pattern, String (*generateReplacement)()) {
  while (true) {
    int index = value.indexOf(pattern);
    if (index == -1) {
      break;
    }
    value = value.substring(0, index) + generateReplacement() + value.substring(index + pattern.length());
  }
  return value;
}

/**
 * Generates a random number, encoded as a hex string.
 */
String getRandom() {
  return String(random(2147483647), HEX);
}

// Single source of truth — all three placeholders below go through
// DeviceIdentity so the strings AP-SSID / WiFi-hostname / MQTT-client
// embed exactly match the canonical id used by the cert CN, the
// mothership deviceId payload, and the AutoUpdate did= query.
// Diverging here is how an operator ends up with a device whose
// AP says one MAC but whose cert says another.

// Lower-case 12-hex MAC. Legacy placeholder name kept for
// backwards-compat with factory_settings.ini files that still use
// "#{unique_id}".
String getUniqueId() {
  return DeviceIdentity::macHex12();
}

// Full canonical id — "<project>-<mac12>-<uid8>" — same string used
// as X.509 Subject CN, mothership deviceId, and AutoUpdate did=. Use
// in slots where length doesn't matter (hostname can be 32+ chars on
// modern OSes, MQTT clientId up to 255).
String getDeviceId() {
  return DeviceIdentity::canonical();
}

// Compact id — "<project>-<uid8>" — drops the MAC segment so the
// result fits the IEEE 802.11 SSID 32-octet cap and DHCP hostname
// practical limit. Still unique per device because uid8 comes from
// the immutable eFuse UID.
String getDeviceIdShort() {
  return DeviceIdentity::projectName() + "-" + DeviceIdentity::uidHex8();
}

String format(String value) {
  value = replaceEach(value, "#{random}", getRandom);
  value.replace("#{unique_id}", getUniqueId());
  value.replace("#{device_id_short}", getDeviceIdShort());
  value.replace("#{device_id}", getDeviceId());
  value.replace("#{platform}", PLATFORM);
  return value;
}

};  // end namespace SettingValue
